# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 561f99ae78d8fa4644bac8ec70e268a18880f6bcb0814cfd365eee41b1e5053e02d2df0676b26a1ddb0a4b3ed838cf8230fba11ee7a0882c76f57d1945b201b4

test:
  secret_key_base: ccd8f3daa468d34996b0539e701a291a90470ceef97a8d3629db945962ff58aeb580a97c645af61947df6dfffaf67288eee7c54dc4942394294e9758eba5c08c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
